### ISSUE TITLE
Handle and URL redirects

### ISSUE THREAD

**Issue by vantuyls** [osulp/dspace2hydra#106]
during migration, you need to capture the handle ID and filename of the dspace item. This information can then be used to:
- [ ] recreate the handle
- [ ] recreate the item URL
- [ ] recreate the bitstream URL

These will then all be redirected to the Parent Work page of that bitstream for the item in Hyrax

**Comment by vantuyls** [comment]
- [ ] Handle of an item redirects to the Work showpage for the item in Hyrax
- [ ] Handle URL for an item redirects to the Work showpage for the item in Hyrax
- [ ] URL for the bitstream redirects to the bitstream in Hyrax

**Comment by vantuyls** [comment]
Okay, i think as an MVP on this we don't necessarily need to map a bitstream download URL in Hyrax. I'm happy, as a starting point (assuming it's easier) to have all of our redirects go to the parent work of a file. 

@revgum has some thoughts about how hard/easy the file direct download is.

**Comment by revgum** [comment]
1. D2H knows;
- the file upload ID (not fileset_id) for the file that was uploaded
- the file name that was uploaded (ie. my_awesome.pdf)
- the DSpace file sequence
- the newly created work ID 

2. DSpace database has;
- bitstream_id related to file sequence for a handle (and/or item id)

3. Hyrax background jobs mint the fileset_id and associate it to the work while it is processing. 

So during migration, D2H doesn't have a reliable mechanism to get the fileset_id for a work until some time after the work was published. So it's not practical to have migration for each item wait until it can get the fileset_ids that were generated in the background.

------------------------- 
Some future ideas;

Bitstream direct downloads could be remapped on the webserver to a file_set download controller which we create a new behavior for to handle translating the bitstream and sequence to what became the new fileset_id and stream the file for download. This would make use of the DSpace database query results (#1) as well as a migration artifact that D2H will need to generate (#2) in order to determine and stream the fileset from the server.

@vantuyls @wickr  Some context around my current thought and understanding of the situation.

**Comment by wickr** [comment]
Either use a separate controller to process incoming or include the fileset IDs in the export of the rewrite map rules that is run after ingest.

So you'd get on export:
Handle > Work ID
Handle/File Download (and/or Sequence) > Fileset ID

**Comment by zhang4952** [comment]
I agree with @revgum that the map is only available after the ingestion is done (when Fedora is updated), which means some time later than running the migration script. 

What D2H and Fedora need to know to map the following two DSpace URIs:
http://ir.library.oregonstate.edu/xmlui/handle/1957/60608
- D2H: handle, hyrax work_id(?)
- fedora: none

http://ir.library.oregonstate.edu/xmlui/bitstream/handle/1957/60608/convex_hull_data_for_Part_I.zip?sequence=2 
we can direct all the bitstreams to its parent item page in Hyrax, which is like in case 1, or
- D2H: handle, filename, sequence_id,  (?)
- fedora: find fileset_id by searching "File Title"?

@revgum ?

**Comment by wickr** [comment]
The Handle should be stored in the Work in http://purl.org/dc/terms/replaces

**Comment by revgum** [comment]
So, a rake task that finds and associates a handle to a work id and/or file set id would solve the mapping problem: https://github.com/osulp/Scholars-Archive/issues/562

And it looks like we need a new field using dct:replaces on SA and to update our configurations to map the handle to the new field. 

@wickr @zhang4952

**Comment by wickr** [comment]
OD rewrite generator: https://github.com/OregonDigital/oregondigital/blob/master/lib/oregon_digital/rewrite_generator.rb

**Comment by revgum** [comment]
See #110

**Comment by revgum** [comment]
replaced by #110 and rake task on SA
