### ISSUE TITLE
LCSH subject not found

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#79]
What should DSpace2Hydra do if it has a subject heading in the metadata that was not returned from LCSH? Pass the original subject heading along to be migrated (rather than a URI to an actual LCSH?) 

Prevent the item from being migrated until it is fixed or removed?

**Comment by revgum** [comment]
An example run where I'm testing out the logging 
```dspace2hydra logging % ruby dspace2hydra.rb -b tmp/bags/ITEM@1957-55523 -c config/etd.yml
Processing ITEM@1957-55523 started at 2017-03-31T14:45:37-07:00
Processing bag
Mapping item metadata
Searching LCSH http://id.loc.gov/search/?q=Giant%20panda--Kungfu&q=http://id.loc.gov/authorities/subjects&format=json
No items parsed in return from LCSH search query
Configuration ('except_empty_value') set for 'subject', will not map an empty value```

**Comment by wickr** [comment]
I know we've discussed this but don't think there was ever a decision, and I can't find much in other tickets.

Options:
A) Put unmatched LCSH as text in Keywords field. Would be indexed and searchable but not faceted, or maybe would be faceted but not together with the other LCSH.
B) Create new subject URIs from unmatched LCSH at opaquenamespace.org.  Would be faceted but have little real meaning/connection to anything else. This may not be any worse than the text we have now with no ID numbers. 
C) Separate/split up compound terms from the ending one until one matches id.loc.gov, then also match the other split off one. Example `A--B--C`, try to match `A--B` and `C`. If I remember correctly splitting them up is not desired for SA, as it can alter the meaning significantly.
D) Look for similar subjects in different vocabularies that could work instead.

**Comment by vantuyls** [comment]
@mlv611 when you spoke with Richard and Laura about the issue of compound LCSH, what was their response? I'm wondering if we need to circle back to them on this issue to dive a little deeper. 

@revgum or @zhang4952 can you provide me with a handful more examples to share with Cataloging?

**Comment by vantuyls** [comment]
From meeting wiht richard:
- [ ] at some point LC was trying to build URIs for composite SH (which is why we had probably been seeing some matches of composite SH
- [ ] richard would prefer that ONS be the place to stage these SH in the hopes that at some point LC will be able to accept them as SH in the future

Ordering:
- [ ] technically, ordering is important, but practically, the ordering of LCSH isn't important
- [ ] BUT, the sequence we see in dspace is probably the same sequence that we see in the MARC record, so if we want to preserve the data integrity, we should preserve ordering

**Comment by revgum** [comment]
We're not passing LCSH uri's anymore, only the original labels
